numero_inteiro= int(input("informe um numero inteiro ->"))
print("o dobro deste numero é ->", numero_inteiro * 2 )
a_quadrado= int(input(" informe a area do quadrado ->")) 
print(" o valor da area do quadrado é ->", a_quadrado * a_quadrado)
idade= int(input(" informe a sua idade ->")) 
print(" a sua idade daqui 365 dias vai ser ->", idade * 365)